// Netlify Edge Function — wraps the TanStack Start / Cloudflare Worker output.
// Both Netlify Edge Functions and Cloudflare Workers run on the V8 isolate model,
// so the built worker.js is fully compatible here.

import type { Context } from "https://edge.netlify.com/";

export default async function handler(
  request: Request,
  context: Context,
): Promise<Response> {
  // Let Netlify serve static assets (.js, .css, fonts, images) directly
  const { pathname } = new URL(request.url);
  const isAsset = /\.(?:js|mjs|css|png|jpe?g|svg|ico|webp|woff2?|ttf|otf|map|json|txt|xml)$/i.test(pathname);
  if (isAsset) {
    return context.next();
  }

  try {
    // Import the built Cloudflare Worker entry point
    // (generated by `npm run build` → `.output/_worker.js`)
    const { default: worker } = await import(
      // @ts-expect-error — resolved from build output at deploy time
      "../../.output/_worker.js"
    );

    // Build a Cloudflare-compatible env object from Netlify env vars
    const env: Record<string, string> = {};
    const keys = [
      "VITE_SUPABASE_URL",
      "VITE_SUPABASE_PUBLISHABLE_KEY",
      "VITE_SUPABASE_PROJECT_ID",
      "SUPABASE_URL",
      "SUPABASE_PUBLISHABLE_KEY",
    ];
    for (const key of keys) {
      const val = Deno.env.get(key);
      if (val) env[key] = val;
    }

    // Cloudflare Workers execution context shim
    const ctx = {
      waitUntil: context.waitUntil.bind(context),
      passThroughOnException: () => { },
    };

    return await worker.fetch(request, env, ctx);
  } catch (err) {
    console.error("[edge/server] Error:", err);
    // Fall back to next Netlify handler (serves static files / 404)
    return context.next();
  }
}

export const config = { path: "/*" };
