/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUpdatePasswordRouteImport } from './routes/_app.update-password'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPredictRouteImport } from './routes/_app.predict'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppBulkRouteImport } from './routes/_app.bulk'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUpdatePasswordRoute = AppUpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPredictRoute = AppPredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBulkRoute = AppBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof AppBulkRoute
  '/dashboard': typeof AppDashboardRoute
  '/predict': typeof AppPredictRoute
  '/profile': typeof AppProfileRoute
  '/update-password': typeof AppUpdatePasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bulk': typeof AppBulkRoute
  '/dashboard': typeof AppDashboardRoute
  '/predict': typeof AppPredictRoute
  '/profile': typeof AppProfileRoute
  '/update-password': typeof AppUpdatePasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/bulk': typeof AppBulkRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/predict': typeof AppPredictRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/update-password': typeof AppUpdatePasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bulk'
    | '/dashboard'
    | '/predict'
    | '/profile'
    | '/update-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bulk'
    | '/dashboard'
    | '/predict'
    | '/profile'
    | '/update-password'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/bulk'
    | '/_app/dashboard'
    | '/_app/predict'
    | '/_app/profile'
    | '/_app/update-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/update-password': {
      id: '/_app/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof AppUpdatePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/predict': {
      id: '/_app/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof AppPredictRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bulk': {
      id: '/_app/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof AppBulkRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBulkRoute: typeof AppBulkRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPredictRoute: typeof AppPredictRoute
  AppProfileRoute: typeof AppProfileRoute
  AppUpdatePasswordRoute: typeof AppUpdatePasswordRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBulkRoute: AppBulkRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPredictRoute: AppPredictRoute,
  AppProfileRoute: AppProfileRoute,
  AppUpdatePasswordRoute: AppUpdatePasswordRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
